project:
  type: website
  output-dir: docs

preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true


website:
  title: "Md Nahin Alam"
  favicon: "the sun fall.jpg"
  
  page-footer:
    center: |
      All rights reserved &copy; 2024 Md Nahin Alam
    background: "#2C3E50"
    
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: teaching.qmd
        text: Teaching
      - href: courses.qmd
        text: Courses
      - href: cv.qmd
        text: CV
    right:
      - icon: linkedin
        href: www.linkedin.com/in/md-nahin-alam
      - text: "<img src='/images/researchgate.svg' alt='ResearchGate' style='height:1.2em; margin-top:-0.2em;'>"
        href: https://www.researchgate.net/profile/Md-Nahin-Alam
    
format:
  html:
    theme:
      light: flatly
      dark: [flatly, darkly]
    smooth-scroll: true
    toc: true

