---
title: "Research"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-link: false
    code-tools: false
    css:
      - research.css
---

## 2024

::: publication
Mehedi Hasan, Leion Hassan, Mamun Abdullah Al, Abu Hena Mustafa Kamal, Mohd Hanafi Idris, Muhammad Ziaul Hoque, Riffat Mahmood, <b>Nahin Alam</b>, Ataher Ali (2024). Human intervention caused massive destruction of the second largest mangrove forest, Chakaria Sundarbans, Bangladesh.\
<em>Environmental Science and Pollution Research</em>, 31, 25329–25341 (2024).\
<a href="https://www.researchgate.net/publication/378860079_Human_intervention_caused_massive_destruction_of_the_second_largest_mangrove_forest_Chakaria_Sundarbans_Bangladesh" target="_blank">PDF</a>
:::

::: publication
**Poster**

Leion Hassan, Md. Enamul Hoque, <b>Nahin Alam</b>, Md. Ibrahim (2024). Understanding Fishing Prospects: Satellite-Based Evaluation of Phytoplankton Phenology in the Northern Bay of Bengal.\
Conference: ICO 2024: International Conference on OceanographyAt: Bangladesh Oceanographic Research Institute, Bangladesh.\
<a href="https://www.researchgate.net/publication/377759712_Understanding_Fishing_Prospects_Satellite-Based_Evaluation_of_Phytoplankton_Phenology_in_the_Northern_Bay_of_Bengal" target="_blank">PDF</a>
:::

## 2022

::: publication
**Conference Paper**

Mehedi Hasan, Leion Hassan, Mamun Abdullah Al, Abu Hena Mustafa Kamal, Mohd Hanafi Idris, Muhammad Ziaul Hoque, Riffat Mahmood, <b>Nahin Alam</b>, Ataher Ali (2022). Human interaction caused land cover changes of Chakaria Sundarban mangrove forest in Bangladesh: a fifty-years study (2022).\
<a href="https://www.researchgate.net/publication/362837157_Human_interaction_caused_land_cover_changes_of_Chakaria_Sundarban_mangrove_forest_in_Bangladesh_a_fifty-years_study" target="_blank">PDF</a>
:::








